name: megancampbellsmith
favicon: null
layout_spectrum: 0.11752223828807473
typography_spectrum: 0.7827393601182848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6560790296643972
  lightness: 0.10144573193974793
  saturation: 0.15145488595589995
  rhythmicContrast: 0.5538795264437795
purpose: []
